language: node_js
node_js:
  - "8"
branches:
  only:
  - dev
cache:
   directories:
     - node_modules
script:
    - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: docs/.vuepress/dist
  target-branch: gh-pages
  on:
    branch: dev
