language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
script:
  - npm run docs:build
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    local-dir: docs/.vuepress/dist
    target-branch: gh-pages
    on:
      branch: master
  - provider: npm
    email: maggie@5milesapp.com
    api_key: $NPM_TOKEN
    on:
      tags: true
